import Formatter from "./format.js";

const
	reviewTemplate = '<li class="list_item"><div><div class="review_area"><div class="thumb_area">{{#if commentImages}}{{#each commentImages}}<a href="#" class="thumb" title="이미지 크게 보기"><img width="90" height="90"class="img_vertical_top"src="./download?fileName={{saveFileName}}&contentType={{contentType}}"alt="리뷰이미지"></a><span class="img_count" style="display: none;">1</span>{{/each}}{{/if}}</div><h4 class="resoc_name">{{#getProductDescription}}{{/getProductDescription}}</h4><p class="review">{{comment}}</p></div><div class="info_area"><div class="review_info"><span class="grade">{{#getFormatScore score}}{{/getFormatScore}}</span><span class="name">{{#getFormatEmail reservationEmail}}{{/getFormatEmail}}</span><span class="date">{{#getFormatDate reservationDate}}{{/getFormatDate}}방문</span></div></div></div></li>',
	infoTabTemplate = '<ul class="info_tab_lst"><li class="item _detail"><a class="anchor active"> <span>상세정보</span></a></li><li class="item _path"><a class="anchor"> <span>오시는길</span></a></li></ul><div class="detail_area_wrap"><div class="detail_area"><div class="detail_info"><h3 class="blind">상세정보</h3><ul class="detail_info_group"><li class="detail_info_lst"><strong class="in_tit">[소개]</strong><p class="in_dsc">{{productContent}}</p></li><li class="detail_info_lst"><strong class="in_tit">[공지사항]</strong><ul class="in_img_group"><li class="in_img_lst"><img alt="" class="img_thumb"src="https://ssl.phinf.net/naverbooking/20170131_238/14858250829398Pnx6_JPEG/%B0%F8%C1%F6%BB%E7%C7%D7.jpg?type=a1000"></li></ul></li></ul></div></div></div><div class="detail_location hide"><div class="box_store_info no_topline"><a class="store_location" title="지도웹으로 연결"><img class="store_map img_thumb" alt="map" src=".download?fileName={{#getSaveFileName}}{{/getSaveFileName}}&contentType={{#getContentType}}{{/getContentType}}"><span class="img_border"></span><span class="btn_map"><i class="spr_book2 ico_mapview"></i></span></a><h3 class="store_name">{{productDescription}}</h3><div class="store_info"><div class="store_addr_wrap"><span class="fn fn-pin2"></span><p class="store_addr_bold">{{placeStreet}}</p><p class="store_addr"><span class="addr_old">지번</span><span class="addr_old_detail">{{placeLot}}</span></p><p class="store_addr addr_detail">{{placeName}}</p></div><div class="lst_store_info_wrap"><ul class="lst_store_info"><li class="item"><span class="item_lt"><i class="fn fn-call2"></i><span class="sr_only">전화번호</span></span><span class="item_rt"><a href="tel:{{telephone}}" class="store_tel">{{telephone}}</a></span></li></ul></div></div><div class="bottm_common_path column2"><a class="btn_path"><i class="fn fn-path-find2"></i><span>길찾기</span></a><a class="btn_navigation before"><i class="fn fn-navigation2"></i><span>내비게이션</span></a></div></div></div>',
	imageTemplate = '<li class="item" style="width: 414px;"><img alt="{{fileName}}" class="img_thumb" src="./download?fileName={{saveFileName}}&contentType={{contentType}}"><span class="img_bg"></span><div class="visual_txt"><div class="visual_txt_inn"><h2 class="visual_txt_tit"><span></span></h2><p class="visual_txt_dsc"></p></div></div></li>',
	priceTemplate = '<div class="qty" data-product-price-id="{{productPriceId}}"><div class="count_control"><div class="clearfix"><a class="btn_plus_minus spr_book2 ico_minus3 disabled"title="빼기"data-value=-1> </a><input type="tel"class="count_control_input disabled" value="0" readonlytitle="수량"><a class="btn_plus_minus spr_book2 ico_plus3"title="더하기"data-value=1> </a></div><div class="individual_price"><span class="total_price">0</span><span class="price_type">원</span></div></div><div class="qty_info_icon"><strong class="product_amount"><span>{{#getTypeName priceTypeName}}{{/getTypeName}}</span></strong><strong class="product_price"><span class="price" data-price="{{price}}">{{#getFormatPrice price}}{{/getFormatPrice}}</span><span class="price_type">원</span></strong><em class="product_dsc">{{#getFormatPrice price}}{{/getFormatPrice}}원 ({{discountRate}}% 할인가)</em></div></div>',
	cardTemplate = '<article class="card_item" data-reservation-info-id={{reservationInfoId}} data-product-id={{productId}}><a class="link_booking_details"><div class="card_body"><div class="left"></div><div class="middle"><div class="card_detail"><em class="booking_number">No.{{reservationInfoId}}</em><h4 class="tit">{{displayInfo.productDescription}}</h4><ul class="detail"><li class="item"><span class="item_tit">일정</span><em class="item_dsc"> {{displayInfo.openingHours}} </em></li><li class="item"><span class="item_tit">장소</span><em class="item_dsc"> {{displayInfo.placeName}} </em></li><li class="item"><span class="item_tit">업체</span><em class="item_dsc"> {{displayInfo.placeStreet}}</em></li></ul><div class="price_summary"><span class="price_tit">결제 예정금액</span><em class="price_amount"><span>{{totalPrice}}</span><span class="unit">원</pan></em></div>{{#if cancelYn}}{{else}}{{#if isComplete}}<div class="booking_cancel"><button class="btn" value="{{reservationInfoId}}"><span>예매자 리뷰 남기기</span></button></div>{{else}}<!-- [D] 예약 신청중, 예약 확정 만 취소가능, 취소 버튼 클릭 시 취소 팝업 활성화 --><div class="booking_cancel"><button class="btn" value="{{reservationInfoId}}"><span>취소</span></button></div>{{/if}}{{/if}}</div></div><div class="right"></div></div><div class="card_footer"><div class="left"></div><div class="middle"></div><div class="right"></div></div></a><a href="#" class="fn fn-share1 naver-splugin btn_goto_share" title="공유하기"></a></article>';

const Bind = {
	registerReviewTemplate(elementText = reviewTemplate, productDescription = {}) {
		Handlebars.registerHelper("getProductDescription", () => productDescription);
		Handlebars.registerHelper("getFormatScore", score => Formatter.formatScore(score));
		Handlebars.registerHelper("getFormatEmail", reservationEmail => Formatter.formatEmail(reservationEmail));
		Handlebars.registerHelper("getFormatDate", reservationDate => Formatter.formatDate(reservationDate));
		return Handlebars.compile(elementText);
	},
	registerInfoTabTemplate(elementText = infoTabTemplate, displayInfoImage = {}) {
		Handlebars.registerHelper("getSaveFileName", () => displayInfoImage.saveFileName);
		Handlebars.registerHelper("getContentType", () => displayInfoImage.contentType);
		return Handlebars.compile(elementText);
	},
	registerImageTemplate(elementText = imageTemplate) {
		return Handlebars.compile(elementText);
	},
	registerPriceTemplate(elementText = priceTemplate, priceTypeList = {}) {
		Handlebars.registerHelper("getTypeName", priceTypeName => priceTypeList[priceTypeName].name);
		Handlebars.registerHelper("getFormatPrice", price => Formatter.formatPrice(price));
		return Handlebars.compile(elementText);
	},
	registerReservationTemplate(elementText = cardTemplate) {
		return Handlebars.compile(elementText);
	}
}
export default Bind;